import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";

import islandScene from "../assets/Island.glb";
import { a } from "@react-spring/three";
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Elin Abrahamsen (https://sketchfab.com/elinab)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/late-night-lessions-daf97264eeba42159b4dfb93a46260c5
Title: Late Night Lessions
*/

const Island = ({ isRotating, setIsRotating, ...props }) => {
  const islandRef = useRef();

  const { gl, viewport } = useThree();
  const lastX = useRef(0);
  const rotationSpeed = useRef(0);
  const dampingFactor = 0.95;

  const handlePointerDown = (e) => {
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(true);

    const clientX = e.touches ? e.touches[0].clientX : e.clientX;
    lastX.current = clientX;
  };

  const handlePointerUp = (e) => {
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(false);
  };

  const handlePointerMove = (e) => {
    e.stopPropagation();
    e.preventDefault();

    if (isRotating) {
      const clientX = e.touches ? e.touches[0].clientX : e.clientX;
      const delta = (clientX - lastX.current) / viewport.width;
      islandRef.current.rotation.y += delta * 0.01 * Math.PI;
      lastX.current = clientX;
      rotationSpeed.current = delta * 0.01 * Math.PI;
    }
  };

  const { nodes, materials } = useGLTF(islandScene);
  useFrame(() => {
    if (!isRotating) {
      rotationSpeed.current *= dampingFactor;
      if (Math.abs(rotationSpeed.current) < 0.001) {
        rotationSpeed.current = 0;
      }

      islandRef.current.rotation.y += rotationSpeed.current;
    } else {
      const rotation = islandRef.current.rotation.y;
    }
  });

  useEffect(() => {
    const canvas = gl.domElement;
    canvas.addEventListener("pointerdown", handlePointerDown);
    canvas.addEventListener("pointerup", handlePointerUp);
    canvas.addEventListener("pointermove", handlePointerMove);

    return () => {
      canvas.removeEventListener("pointerdown", handlePointerDown);
      canvas.removeEventListener("pointerup", handlePointerUp);
      canvas.removeEventListener("pointermove", handlePointerMove);
    };
  }, [gl, handlePointerDown, handlePointerMove, handlePointerUp]);
  return (
    <a.group {...props} ref={islandRef}>
      <group position={[1.8, 1.5, -1.3]} scale={[0.2, 1, 0.2]}>
        <mesh geometry={nodes.Object_10.geometry} material={materials.phong2} />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials.phong50}
        />
      </group>
      <group position={[0, 3, 0]} scale={[4.2, 0.7, 3.6]}>
        <mesh
          geometry={nodes.Object_15.geometry}
          material={materials.phong31}
        />
        <mesh
          geometry={nodes.Object_17.geometry}
          material={materials.phong44}
        />
        <mesh
          geometry={nodes.Object_19.geometry}
          material={materials.phong43}
        />
      </group>
      <group position={[1.8, 0.4, -1.3]} scale={[0.3, 0.1, 0.3]}>
        <mesh geometry={nodes.Object_22.geometry} material={materials.phong2} />
        <mesh
          geometry={nodes.Object_24.geometry}
          material={materials.phong51}
        />
      </group>
      <group position={[1.8, 2.5, -1.3]} scale={[0.3, 0.1, 0.3]}>
        <mesh
          geometry={nodes.Object_27.geometry}
          material={materials.phong50}
        />
        <mesh geometry={nodes.Object_29.geometry} material={materials.phong2} />
      </group>
      <mesh
        geometry={nodes.Object_32.geometry}
        material={materials.phong2}
        position={[1.8, 1.5, 1.3]}
        scale={[0.2, 1, 0.2]}
      />
      <group position={[1.8, 2.5, 1.3]} scale={[0.3, 0.1, 0.3]}>
        <mesh
          geometry={nodes.Object_35.geometry}
          material={materials.phong50}
        />
        <mesh geometry={nodes.Object_37.geometry} material={materials.phong2} />
      </group>
      <group position={[1.8, 0.4, 1.3]} scale={[0.3, 0.1, 0.3]}>
        <mesh geometry={nodes.Object_40.geometry} material={materials.phong2} />
        <mesh
          geometry={nodes.Object_42.geometry}
          material={materials.phong51}
        />
      </group>
      <group position={[-1.8, 2.5, -1.3]} scale={[0.3, 0.1, 0.3]}>
        <mesh
          geometry={nodes.Object_45.geometry}
          material={materials.phong50}
        />
        <mesh geometry={nodes.Object_47.geometry} material={materials.phong2} />
      </group>
      <mesh
        geometry={nodes.Object_50.geometry}
        material={materials.phong2}
        position={[-1.8, 1.5, -1.3]}
        scale={[0.2, 1, 0.2]}
      />
      <group position={[-1.8, 0.4, -1.3]} scale={[0.3, 0.1, 0.3]}>
        <mesh geometry={nodes.Object_53.geometry} material={materials.phong2} />
        <mesh
          geometry={nodes.Object_55.geometry}
          material={materials.phong51}
        />
      </group>
      <mesh
        geometry={nodes.Object_58.geometry}
        material={materials.phong2}
        position={[-1.8, 1.5, 1.3]}
        scale={[0.2, 1, 0.2]}
      />
      <group position={[-1.8, 0.4, 1.3]} scale={[0.3, 0.1, 0.3]}>
        <mesh geometry={nodes.Object_61.geometry} material={materials.phong2} />
        <mesh
          geometry={nodes.Object_63.geometry}
          material={materials.phong51}
        />
      </group>
      <group position={[-1.8, 2.5, 1.3]} scale={[0.3, 0.1, 0.3]}>
        <mesh
          geometry={nodes.Object_66.geometry}
          material={materials.phong50}
        />
        <mesh geometry={nodes.Object_68.geometry} material={materials.phong2} />
      </group>
      <mesh
        geometry={nodes.Object_71.geometry}
        material={materials.lambert1}
        position={[0, 0, -1.6]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[0.1, 3.2, 0]}
      />
      <mesh
        geometry={nodes.Object_74.geometry}
        material={materials.phong8}
        position={[0, 1.3, -1.6]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[1, 1, 0.3]}
      />
      <mesh
        geometry={nodes.Object_77.geometry}
        material={materials.phong8}
        position={[-1.9, 1.3, -0.3]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[1, 1, 0.3]}
      />
      <group position={[1.8, 2.2, 0]} scale={[0.1, 0.2, 2.3]}>
        <mesh
          geometry={nodes.Object_80.geometry}
          material={materials.phong27}
        />
        <mesh
          geometry={nodes.Object_82.geometry}
          material={materials.phong45}
        />
        <mesh
          geometry={nodes.Object_84.geometry}
          material={materials.phong46}
        />
      </group>
      <group
        position={[1.8, 2.3, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.2, 0.2, 0.8]}
      >
        <mesh
          geometry={nodes.Object_87.geometry}
          material={materials.phong46}
        />
        <mesh
          geometry={nodes.Object_89.geometry}
          material={materials.phong27}
        />
      </group>
      <group
        position={[-1.3, 2.2, 1.3]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.1, 0.2, 1.7]}
      >
        <mesh
          geometry={nodes.Object_92.geometry}
          material={materials.phong46}
        />
        <mesh
          geometry={nodes.Object_94.geometry}
          material={materials.phong45}
        />
        <mesh
          geometry={nodes.Object_96.geometry}
          material={materials.phong27}
        />
      </group>
      <group
        position={[-0.7, 2.4, 1.3]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.2, 0.2, 0.7]}
      >
        <mesh
          geometry={nodes.Object_99.geometry}
          material={materials.phong46}
        />
        <mesh
          geometry={nodes.Object_101.geometry}
          material={materials.phong27}
        />
      </group>
      <group
        position={[0.6, 2.4, 1.3]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.2, 0.2, 0.7]}
      >
        <mesh
          geometry={nodes.Object_104.geometry}
          material={materials.phong46}
        />
        <mesh
          geometry={nodes.Object_106.geometry}
          material={materials.phong27}
        />
      </group>
      <group
        position={[1.2, 2.2, 1.3]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.1, 0.2, 1.7]}
      >
        <mesh
          geometry={nodes.Object_109.geometry}
          material={materials.phong46}
        />
        <mesh
          geometry={nodes.Object_111.geometry}
          material={materials.phong45}
        />
        <mesh
          geometry={nodes.Object_113.geometry}
          material={materials.phong27}
        />
      </group>
      <group position={[1.8, 0.8, 0]} scale={[0.1, 0.1, 2.3]}>
        <mesh
          geometry={nodes.Object_116.geometry}
          material={materials.phong27}
        />
        <mesh
          geometry={nodes.Object_118.geometry}
          material={materials.phong45}
        />
        <mesh
          geometry={nodes.Object_120.geometry}
          material={materials.phong46}
        />
      </group>
      <mesh
        geometry={nodes.Object_123.geometry}
        material={materials.phong2}
        position={[1.8, 0.4, 0]}
        scale={[0.1, 0.1, 2.3]}
      />
      <mesh
        geometry={nodes.Object_126.geometry}
        material={materials.phong27}
        position={[1.8, 0.6, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0, 1.2, 0]}
      />
      <mesh
        geometry={nodes.Object_129.geometry}
        material={materials.phong27}
        position={[1.8, 0.7, 0]}
        scale={[0, 0.1, 0]}
      />
      <group position={[1.8, 0.6, 0.8]} scale={0.1}>
        <mesh
          geometry={nodes.Object_132.geometry}
          material={materials.phong19}
        />
        <mesh
          geometry={nodes.Object_134.geometry}
          material={materials.phong53}
        />
        <mesh
          geometry={nodes.Object_136.geometry}
          material={materials.phong54}
        />
      </group>
      <mesh
        geometry={nodes.Object_139.geometry}
        material={materials.phong27}
        position={[1.8, 0.7, 0.8]}
        scale={[0, 0.2, 0]}
      />
      <mesh
        geometry={nodes.Object_142.geometry}
        material={materials.phong27}
        position={[1.8, 0.7, 0.4]}
        scale={[0, 0.1, 0]}
      />
      <mesh
        geometry={nodes.Object_145.geometry}
        material={materials.phong27}
        position={[1.8, 0.7, -0.8]}
        scale={[0, 0.2, 0]}
      />
      <mesh
        geometry={nodes.Object_148.geometry}
        material={materials.phong27}
        position={[1.8, 0.7, -0.4]}
        scale={[0, 0.1, 0]}
      />
      <mesh
        geometry={nodes.Object_151.geometry}
        material={materials.phong13}
        scale={[4.1, 0.4, 3.3]}
      />
      <group position={[0, 0.3, 0]} scale={[4.2, 0.2, 3.4]}>
        <mesh
          geometry={nodes.Object_154.geometry}
          material={materials.phong55}
        />
        <mesh
          geometry={nodes.Object_156.geometry}
          material={materials.phong24}
        />
        <mesh
          geometry={nodes.Object_158.geometry}
          material={materials.phong56}
        />
      </group>
      <group position={[0, 0, -0.1]} scale={[0.7, 1, 1]}>
        <mesh
          geometry={nodes.Object_161.geometry}
          material={materials.phong13}
        />
        <mesh
          geometry={nodes.Object_163.geometry}
          material={materials.phong33}
        />
        <mesh
          geometry={nodes.Object_165.geometry}
          material={materials.phong35}
        />
        <mesh
          geometry={nodes.Object_167.geometry}
          material={materials.phong34}
        />
      </group>
      <group scale={[-1, 1, 1]}>
        <mesh
          geometry={nodes.Object_220.geometry}
          material={materials.phong4}
          position={[0, -1.2, 0]}
          scale={[1, 1.6, 1]}
        />
        <mesh
          geometry={nodes.Object_206.geometry}
          material={materials.phong4}
        />
        <mesh
          geometry={nodes.Object_209.geometry}
          material={materials.phong3}
        />
        <mesh
          geometry={nodes.Object_212.geometry}
          material={materials.phong3}
        />
        <mesh
          geometry={nodes.Object_215.geometry}
          material={materials.phong1}
        />
        <mesh
          geometry={nodes.Object_217.geometry}
          material={materials.phong40}
        />
        <mesh
          geometry={nodes.Object_223.geometry}
          material={materials.phong3}
        />
        <mesh
          geometry={nodes.Object_226.geometry}
          material={materials.phong1}
        />
        <mesh
          geometry={nodes.Object_228.geometry}
          material={materials.phong40}
        />
      </group>
      <group rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh
          geometry={nodes.Object_246.geometry}
          material={materials.phong4}
          position={[0, -1.2, 0]}
          scale={[1, 1.6, 1]}
        />
        <mesh
          geometry={nodes.Object_232.geometry}
          material={materials.phong4}
        />
        <mesh
          geometry={nodes.Object_235.geometry}
          material={materials.phong3}
        />
        <mesh
          geometry={nodes.Object_238.geometry}
          material={materials.phong3}
        />
        <mesh
          geometry={nodes.Object_241.geometry}
          material={materials.phong1}
        />
        <mesh
          geometry={nodes.Object_243.geometry}
          material={materials.phong40}
        />
        <mesh
          geometry={nodes.Object_249.geometry}
          material={materials.phong3}
        />
        <mesh
          geometry={nodes.Object_252.geometry}
          material={materials.phong1}
        />
        <mesh
          geometry={nodes.Object_254.geometry}
          material={materials.phong40}
        />
      </group>
      <group rotation={[-Math.PI, 0, Math.PI]} scale={[-1, 1, 1]}>
        <mesh
          geometry={nodes.Object_272.geometry}
          material={materials.phong4}
          position={[0, -1.2, 0]}
          scale={[1, 1.6, 1]}
        />
        <mesh
          geometry={nodes.Object_258.geometry}
          material={materials.phong4}
        />
        <mesh
          geometry={nodes.Object_261.geometry}
          material={materials.phong3}
        />
        <mesh
          geometry={nodes.Object_264.geometry}
          material={materials.phong3}
        />
        <mesh
          geometry={nodes.Object_267.geometry}
          material={materials.phong1}
        />
        <mesh
          geometry={nodes.Object_269.geometry}
          material={materials.phong40}
        />
        <mesh
          geometry={nodes.Object_275.geometry}
          material={materials.phong3}
        />
        <mesh
          geometry={nodes.Object_278.geometry}
          material={materials.phong1}
        />
        <mesh
          geometry={nodes.Object_280.geometry}
          material={materials.phong40}
        />
      </group>
      <mesh
        geometry={nodes.Object_283.geometry}
        material={materials.phong28}
        position={[1.2, -0.3, 1.9]}
        scale={[0.4, 0, 0.4]}
      />
      <mesh
        geometry={nodes.Object_286.geometry}
        material={materials.phong29}
        position={[1.7, -0.3, 2]}
        rotation={[0, 1.6, 0]}
        scale={[0.4, 0, 0.4]}
      />
      <mesh
        geometry={nodes.Object_289.geometry}
        material={materials.phong20}
        position={[1.4, -0.3, 2.4]}
        scale={[0.4, 0, 0.4]}
      />
      <mesh
        geometry={nodes.Object_292.geometry}
        material={materials.phong28}
        position={[1.9, -0.3, 2.3]}
        scale={[0.4, 0, 0.4]}
      />
      <mesh
        geometry={nodes.Object_295.geometry}
        material={materials.phong29}
        position={[1.5, -0.3, 2.7]}
        scale={[0.4, 0, 0.4]}
      />
      <mesh
        geometry={nodes.Object_298.geometry}
        material={materials.phong28}
        position={[1.1, -0.3, 2.7]}
        rotation={[0, 0.7, 0]}
        scale={[0.4, 0, 0.4]}
      />
      <mesh
        geometry={nodes.Object_301.geometry}
        material={materials.phong28}
        position={[1.3, -0.3, 3]}
        rotation={[0, 0.7, 0]}
        scale={[0.4, 0, 0.4]}
      />
      <mesh
        geometry={nodes.Object_304.geometry}
        material={materials.phong28}
        position={[2.2, -0.4, 1.9]}
        scale={[0.4, 0, 0.4]}
      />
      <mesh
        geometry={nodes.Object_307.geometry}
        material={materials.phong29}
        position={[2.2, -0.3, 2.1]}
        scale={[0.4, 0, 0.4]}
      />
      <mesh
        geometry={nodes.Object_310.geometry}
        material={materials.phong20}
        position={[1.9, -0.3, 2.7]}
        scale={[0.4, 0, 0.4]}
      />
      <mesh
        geometry={nodes.Object_313.geometry}
        material={materials.phong28}
        position={[2.5, -0.3, 2.6]}
        rotation={[-Math.PI, 0.1, -Math.PI]}
        scale={[0.4, 0, 0.4]}
      />
      <mesh
        geometry={nodes.Object_316.geometry}
        material={materials.phong21}
        position={[1.1, -0.3, 3]}
        rotation={[0, -1.1, 0]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_319.geometry}
        material={materials.phong30}
        position={[0.9, -0.3, 2.9]}
        rotation={[0, -0.1, 0]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_322.geometry}
        material={materials.phong21}
        position={[2.2, -0.3, 1.4]}
        rotation={[-Math.PI, 0.4, -Math.PI]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_325.geometry}
        material={materials.phong21}
        position={[2.4, -0.3, 1.5]}
        rotation={[-Math.PI, 0.1, -Math.PI]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_328.geometry}
        material={materials.phong30}
        position={[2.3, -0.3, 1.1]}
        rotation={[-Math.PI, 1.1, -Math.PI]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_331.geometry}
        material={materials.phong21}
        position={[2.3, -0.3, 0.9]}
        rotation={[0, 1.4, 0]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_334.geometry}
        material={materials.phong21}
        position={[2.5, -0.3, 0.9]}
        rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_337.geometry}
        material={materials.phong21}
        position={[2.3, -0.3, 0.6]}
        rotation={[-Math.PI, 0.3, -Math.PI]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_340.geometry}
        material={materials.phong30}
        position={[2.5, -0.3, 0.7]}
        rotation={[-Math.PI, -0.4, -Math.PI]}
        scale={[0.3, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_343.geometry}
        material={materials.phong21}
        position={[2.3, -0.3, 0.1]}
        rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_346.geometry}
        material={materials.phong21}
        position={[2.2, -0.3, 1.3]}
        rotation={[-Math.PI, 0.5, -Math.PI]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_349.geometry}
        material={materials.phong21}
        position={[2.4, -0.3, 1.1]}
        rotation={[-3, 0.2, -3.1]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_352.geometry}
        material={materials.phong30}
        position={[2.4, -0.3, 1.4]}
        rotation={[-Math.PI, -0.4, -Math.PI]}
        scale={[0.3, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_355.geometry}
        material={materials.phong21}
        position={[2.4, -0.3, 1.2]}
        rotation={[-Math.PI, -0.4, -Math.PI]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_358.geometry}
        material={materials.phong30}
        position={[2.4, -0.3, 0.4]}
        rotation={[-Math.PI, -1.5, -Math.PI]}
        scale={[0.3, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_361.geometry}
        material={materials.phong30}
        position={[2.3, -0.3, 0.7]}
        rotation={[0, 1.5, 0]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_364.geometry}
        material={materials.phong30}
        position={[2.4, -0.3, -0.1]}
        rotation={[-Math.PI, 1, -Math.PI]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_367.geometry}
        material={materials.phong21}
        position={[2.3, -0.3, -0.3]}
        rotation={[0, 1.5, 0]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_370.geometry}
        material={materials.phong30}
        position={[2.3, -0.3, -0.5]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_373.geometry}
        material={materials.phong21}
        position={[2.3, -0.3, -0.6]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_376.geometry}
        material={materials.phong21}
        position={[2.3, -0.3, -0.8]}
        rotation={[-Math.PI, 0.1, -Math.PI]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_379.geometry}
        material={materials.phong30}
        position={[2.3, -0.3, -1]}
        rotation={[-Math.PI, 1.3, -Math.PI]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_382.geometry}
        material={materials.phong21}
        position={[2.6, -0.3, 1.2]}
        rotation={[0, -1.1, 0]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_385.geometry}
        material={materials.phong21}
        position={[2.5, -0.3, -0.2]}
        rotation={[-3.1, 0.5, 3.1]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_388.geometry}
        material={materials.phong30}
        position={[2.6, -0.3, 0.2]}
        rotation={[-3.1, -0.7, 3.1]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_391.geometry}
        material={materials.phong21}
        position={[2.5, -0.3, 0.4]}
        rotation={[-3.1, 0.8, 3.1]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_394.geometry}
        material={materials.phong21}
        position={[2.5, -0.3, 0.1]}
        rotation={[-3, -0.1, -3.1]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_397.geometry}
        material={materials.phong30}
        position={[2.6, -0.3, 1]}
        rotation={[3, -0.2, -3.1]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_400.geometry}
        material={materials.phong30}
        position={[2.6, -0.3, 1.5]}
        rotation={[0, 1.1, 0]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_403.geometry}
        material={materials.phong21}
        position={[2.2, -0.3, -1.4]}
        rotation={[-Math.PI, -1.5, -Math.PI]}
        scale={[0.3, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_406.geometry}
        material={materials.phong21}
        position={[2.2, -0.3, -1.6]}
        rotation={[-3.1, 0.5, 3.1]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_409.geometry}
        material={materials.phong21}
        position={[2.3, -0.3, -1.2]}
        rotation={[-Math.PI, -0.4, -Math.PI]}
        scale={[0.3, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_412.geometry}
        material={materials.phong30}
        position={[2.4, -0.3, -1.3]}
        rotation={[-3.1, -0.7, 3.1]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_415.geometry}
        material={materials.phong21}
        position={[2.5, -0.3, -1]}
        rotation={[0, 1.5, 0]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_418.geometry}
        material={materials.phong21}
        position={[2.5, -0.3, -0.5]}
        rotation={[-Math.PI, -1, -Math.PI]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_421.geometry}
        material={materials.phong21}
        position={[2.5, -0.3, 1.7]}
        rotation={[0, 1.5, 0]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_424.geometry}
        material={materials.phong30}
        position={[-1.2, -0.3, 2.3]}
        rotation={[0, 0.3, 0]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_427.geometry}
        material={materials.phong21}
        position={[-1.3, -0.3, 2.1]}
        rotation={[2.7, 1.3, -2.6]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_430.geometry}
        material={materials.phong21}
        position={[-1.5, -0.3, 2.2]}
        rotation={[-Math.PI, -0.5, -Math.PI]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_433.geometry}
        material={materials.phong30}
        position={[-1.5, -0.3, 2]}
        rotation={[-Math.PI, 1.1, -Math.PI]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_436.geometry}
        material={materials.phong21}
        position={[-1.7, -0.3, 2]}
        rotation={[-Math.PI, 1.2, -Math.PI]}
        scale={[0.3, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_439.geometry}
        material={materials.phong30}
        position={[-1.4, -0.3, 2]}
        rotation={[-0.4, 1.3, 0.5]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_442.geometry}
        material={materials.phong21}
        position={[-1.6, -0.3, 2.2]}
        rotation={[-Math.PI, -0.9, -Math.PI]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_445.geometry}
        material={materials.phong21}
        position={[-1.6, -0.3, 1.8]}
        rotation={[0, 1.1, 0]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_448.geometry}
        material={materials.phong21}
        position={[-1.2, -0.3, 2]}
        rotation={[0, -0.1, 0]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_451.geometry}
        material={materials.phong21}
        position={[-1.5, -0.3, 1.8]}
        rotation={[0, 0.5, 0]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_454.geometry}
        material={materials.phong21}
        position={[-1.8, -0.3, 2]}
        rotation={[0, 1.5, 0]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_457.geometry}
        material={materials.phong30}
        position={[-1.7, -0.3, 1.8]}
        rotation={[0, 1.2, 0]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_460.geometry}
        material={materials.phong30}
        position={[-1.2, -0.3, 1.8]}
        rotation={[0, -0.1, 0]}
        scale={[0.3, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_463.geometry}
        material={materials.phong21}
        position={[-1.4, -0.3, 2.3]}
        rotation={[0, 0.2, 0]}
        scale={[0.3, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_466.geometry}
        material={materials.phong30}
        position={[-1.8, -0.3, 2.2]}
        rotation={[-Math.PI, 0.5, -Math.PI]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_469.geometry}
        material={materials.phong21}
        position={[-2, -0.3, 2.1]}
        rotation={[-3, 1, 3.1]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_472.geometry}
        material={materials.phong21}
        position={[-2.1, -0.3, 1.9]}
        rotation={[0, 1.5, 0]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_475.geometry}
        material={materials.phong21}
        position={[-2, -0.3, 1.8]}
        rotation={[-Math.PI, 0.1, -Math.PI]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_478.geometry}
        material={materials.phong30}
        position={[-1.9, -0.3, 1.9]}
        rotation={[0.6, 1.4, -0.5]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_481.geometry}
        material={materials.phong30}
        position={[-1.2, -0.3, 2.7]}
        rotation={[-2, -1.3, -2]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_484.geometry}
        material={materials.phong21}
        position={[-1.9, -0.3, 2.7]}
        rotation={[-Math.PI, 0.4, -Math.PI]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_487.geometry}
        material={materials.phong21}
        position={[-1.7, -0.3, 2.8]}
        rotation={[-Math.PI, -0.2, -Math.PI]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_490.geometry}
        material={materials.phong30}
        position={[-1.6, -0.3, 2.8]}
        rotation={[-Math.PI, -0.8, -Math.PI]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_493.geometry}
        material={materials.phong21}
        position={[-1.5, -0.3, 2.9]}
        rotation={[-Math.PI, -0.9, -Math.PI]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_496.geometry}
        material={materials.phong21}
        position={[-1.5, -0.3, 2.7]}
        rotation={[0, -1.4, 0]}
        scale={[0.3, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_499.geometry}
        material={materials.phong21}
        position={[-1.9, -0.3, 2.3]}
        rotation={[-Math.PI, 0.4, -Math.PI]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_502.geometry}
        material={materials.phong30}
        position={[-1.7, -0.3, 2.3]}
        rotation={[-Math.PI, 0.1, -Math.PI]}
        scale={[0.3, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_505.geometry}
        material={materials.phong21}
        position={[-1.6, -0.3, 2.5]}
        rotation={[0, 0.2, 0]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_508.geometry}
        material={materials.phong30}
        position={[-1.6, -0.3, 2.6]}
        rotation={[0, -1.4, 0]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_511.geometry}
        material={materials.phong30}
        position={[-1.8, -0.3, 2.6]}
        rotation={[-2.9, -1.1, -2.9]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_514.geometry}
        material={materials.phong21}
        position={[-1.8, -0.3, 2.5]}
        rotation={[2.1, -1.5, 2.2]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_517.geometry}
        material={materials.phong21}
        position={[-1.9, -0.3, 2.6]}
        rotation={[-Math.PI, -0.5, -Math.PI]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_520.geometry}
        material={materials.phong21}
        position={[-1.5, -0.3, 2.5]}
        rotation={[0, 1.4, 0]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_523.geometry}
        material={materials.phong21}
        position={[-1.3, -0.3, 2.6]}
        rotation={[0, -0.7, 0]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_526.geometry}
        material={materials.phong21}
        position={[-1.3, -0.3, 2.7]}
        rotation={[-Math.PI, -1.2, -Math.PI]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_529.geometry}
        material={materials.phong21}
        position={[-1.2, -0.3, 2.8]}
        rotation={[2.9, -1.1, 3]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_532.geometry}
        material={materials.phong21}
        position={[-1.2, -0.3, 2.5]}
        rotation={[0, -1.6, 0]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_535.geometry}
        material={materials.phong30}
        position={[-1.3, -0.3, 3]}
        rotation={[0, -0.4, 0]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_538.geometry}
        material={materials.phong21}
        position={[-1.3, -0.3, 2.4]}
        rotation={[3, -0.1, -3.1]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_541.geometry}
        material={materials.phong30}
        position={[-1.2, -0.3, 2.1]}
        rotation={[3.1, 0, -3.1]}
        scale={0.1}
      />
      <mesh
        geometry={nodes.Object_544.geometry}
        material={materials.phong30}
        position={[-2, -0.3, 2.4]}
        rotation={[-Math.PI, 0.7, -Math.PI]}
        scale={[0.3, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_547.geometry}
        material={materials.phong21}
        position={[-2, -0.3, 2.2]}
        rotation={[-Math.PI, 0.7, -Math.PI]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_550.geometry}
        material={materials.phong30}
        position={[-2.1, -0.3, 2.1]}
        rotation={[0, -0.7, 0]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_553.geometry}
        material={materials.phong30}
        position={[-2.2, -0.3, 1.7]}
        rotation={[0, -1.3, 0]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_556.geometry}
        material={materials.phong21}
        position={[-2.2, -0.3, 1.9]}
        rotation={[0, 0.8, 0]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_559.geometry}
        material={materials.phong21}
        position={[-2.1, -0.3, 2.3]}
        rotation={[0, 0.1, 0]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_562.geometry}
        material={materials.phong30}
        position={[-2.1, -0.3, 2.7]}
        rotation={[0, -0.1, 0]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_565.geometry}
        material={materials.phong30}
        position={[-2.2, -0.3, 2.4]}
        rotation={[0, -0.6, 0]}
        scale={[0.3, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_568.geometry}
        material={materials.phong30}
        position={[-2.1, -0.3, 2.6]}
        rotation={[0, 1.3, 0]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_571.geometry}
        material={materials.phong30}
        position={[-1.8, -0.3, 2.9]}
        rotation={[0, -0.1, 0]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_574.geometry}
        material={materials.phong21}
        position={[-1.1, -0.3, 2.9]}
        rotation={[3, 0.1, -3.1]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_577.geometry}
        material={materials.phong21}
        position={[-0.9, -0.3, 2.9]}
        rotation={[0, -0.7, 0]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_580.geometry}
        material={materials.phong30}
        position={[-1, -0.3, 3]}
        rotation={[3, -0.9, 3.1]}
        scale={[0.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Object_583.geometry}
        material={materials.phong22}
        position={[0.9, -0.2, 2.2]}
        rotation={[0, 0.5, 0]}
        scale={0.4}
      />
      <mesh
        geometry={nodes.Object_586.geometry}
        material={materials.phong22}
        position={[2.7, -0.2, 2.9]}
        rotation={[-Math.PI, 1.5, -Math.PI]}
        scale={0.4}
      />
      <mesh
        geometry={nodes.Object_589.geometry}
        material={materials.phong22}
        position={[4.2, -0.2, 2.5]}
        rotation={[-Math.PI, 0.1, -Math.PI]}
        scale={0.4}
      />
      <mesh
        geometry={nodes.Object_592.geometry}
        material={materials.phong22}
        position={[0.5, -0.3, 3.5]}
        rotation={[-0.1, 0.9, 0.1]}
        scale={0.3}
      />
      <mesh
        geometry={nodes.Object_595.geometry}
        material={materials.phong22}
        position={[3.5, -0.2, -1.8]}
        rotation={[-Math.PI, -1, -Math.PI]}
        scale={0.4}
      />
      <mesh
        geometry={nodes.Object_598.geometry}
        material={materials.phong22}
        position={[2, -0.2, -2.8]}
        rotation={[0, -1.3, 0]}
        scale={0.4}
      />
      <mesh
        geometry={nodes.Object_601.geometry}
        material={materials.phong22}
        position={[2.9, -0.2, 0]}
        rotation={[-Math.PI, 1.3, -Math.PI]}
        scale={0.4}
      />
      <mesh
        geometry={nodes.Object_604.geometry}
        material={materials.phong22}
        position={[0.2, -0.2, 3.6]}
        rotation={[-Math.PI, 0.4, -Math.PI]}
        scale={0.4}
      />
      <mesh
        geometry={nodes.Object_607.geometry}
        material={materials.phong22}
        position={[-1.4, -0.2, 1.2]}
        rotation={[-Math.PI, -1.1, -Math.PI]}
        scale={0.3}
      />
      <mesh
        geometry={nodes.Object_610.geometry}
        material={materials.phong22}
        position={[-2.7, -0.2, 1.4]}
        rotation={[0, -0.8, 0]}
        scale={0.3}
      />
      <mesh
        geometry={nodes.Object_613.geometry}
        material={materials.phong22}
        position={[-0.6, -0.2, 3.2]}
        rotation={[-Math.PI, 0.8, -Math.PI]}
        scale={0.4}
      />
      <mesh
        geometry={nodes.Object_656.geometry}
        material={materials.phong2}
        position={[-1.8, 0.4, 0]}
        scale={[0.1, 0.1, 2.3]}
      />
      <mesh
        geometry={nodes.Object_659.geometry}
        material={materials.phong2}
        position={[0, 0.4, -1.5]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.1, 0.1, 3.3]}
      />
      <group position={[-1.1, 0, 2]} rotation={[0, Math.PI / 4, 0]} scale={0.9}>
        <mesh
          geometry={nodes.Object_663.geometry}
          material={materials.phong9}
          position={[1.7, 0.2, 2.5]}
          rotation={[0, 0, Math.PI / 2]}
          scale={0}
        />
        <mesh
          geometry={nodes.Object_666.geometry}
          material={materials.phong9}
          position={[2.1, 0.2, 2.5]}
          rotation={[0, 0, Math.PI / 2]}
          scale={0}
        />
      </group>
      <mesh
        geometry={nodes.Object_669.geometry}
        material={materials.phong31}
        position={[0.6, 3.2, 1.4]}
        rotation={[0.4, 0, 0]}
        scale={[0.1, 0.3, 0]}
      />
      <group position={[0, -0.2, 0.6]} rotation={[-0.2, 0, 0]}>
        <mesh
          geometry={nodes.Object_673.geometry}
          material={materials.phong6}
        />
        <mesh
          geometry={nodes.Object_676.geometry}
          material={materials.phong6}
        />
        <mesh
          geometry={nodes.Object_679.geometry}
          material={materials.phong6}
        />
        <mesh
          geometry={nodes.Object_682.geometry}
          material={materials.phong6}
        />
        <mesh
          geometry={nodes.Object_685.geometry}
          material={materials.phong6}
        />
        <mesh
          geometry={nodes.Object_688.geometry}
          material={materials.phong6}
        />
        <mesh
          geometry={nodes.Object_691.geometry}
          material={materials.phong31}
        />
        <mesh
          geometry={nodes.Object_693.geometry}
          material={materials.phong43}
        />
        <mesh
          geometry={nodes.Object_696.geometry}
          material={materials.phong43}
        />
        <mesh
          geometry={nodes.Object_698.geometry}
          material={materials.phong31}
        />
        <mesh
          geometry={nodes.Object_701.geometry}
          material={materials.phong43}
        />
        <mesh
          geometry={nodes.Object_703.geometry}
          material={materials.phong31}
        />
        <mesh
          geometry={nodes.Object_706.geometry}
          material={materials.phong31}
        />
        <mesh
          geometry={nodes.Object_708.geometry}
          material={materials.phong43}
        />
        <mesh
          geometry={nodes.Object_711.geometry}
          material={materials.phong7}
        />
      </group>
      <mesh
        geometry={nodes.Object_714.geometry}
        material={materials.phong31}
        position={[-0.5, 3.2, 1.4]}
        rotation={[0.4, 0, 0]}
        scale={[0.1, 0.3, 0]}
      />
      <group position={[0, -0.1, -0.1]}>
        <mesh
          geometry={nodes.Object_717.geometry}
          material={materials.phong65}
        />
        <mesh
          geometry={nodes.Object_719.geometry}
          material={materials.phong16}
        />
      </group>
      <group position={[0.6, 0, 0.5]} rotation={[0, -0.3, 0]}>
        <mesh
          geometry={nodes.Object_723.geometry}
          material={materials.phong17}
        />
        <mesh
          geometry={nodes.Object_725.geometry}
          material={materials.phong63}
        />
        <mesh
          geometry={nodes.Object_728.geometry}
          material={materials.phong17}
        />
        <mesh
          geometry={nodes.Object_730.geometry}
          material={materials.phong64}
        />
        <mesh
          geometry={nodes.Object_733.geometry}
          material={materials.phong17}
        />
        <mesh
          geometry={nodes.Object_735.geometry}
          material={materials.phong63}
        />
        <mesh
          geometry={nodes.Object_738.geometry}
          material={materials.phong17}
        />
        <mesh
          geometry={nodes.Object_740.geometry}
          material={materials.phong63}
        />
        <mesh
          geometry={nodes.Object_743.geometry}
          material={materials.phong17}
        />
        <mesh
          geometry={nodes.Object_746.geometry}
          material={materials.phong18}
        />
        <mesh
          geometry={nodes.Object_748.geometry}
          material={materials.phong62}
        />
        <mesh
          geometry={nodes.Object_751.geometry}
          material={materials.phong17}
        />
        <mesh
          geometry={nodes.Object_753.geometry}
          material={materials.phong63}
        />
        <mesh
          geometry={nodes.Object_756.geometry}
          material={materials.phong17}
        />
        <mesh
          geometry={nodes.Object_758.geometry}
          material={materials.phong63}
        />
        <mesh
          geometry={nodes.Object_761.geometry}
          material={materials.phong17}
        />
        <mesh
          geometry={nodes.Object_763.geometry}
          material={materials.phong63}
        />
        <mesh
          geometry={nodes.Object_766.geometry}
          material={materials.phong17}
        />
        <mesh
          geometry={nodes.Object_768.geometry}
          material={materials.phong63}
        />
        <mesh
          geometry={nodes.Object_771.geometry}
          material={materials.phong17}
        />
        <mesh
          geometry={nodes.Object_773.geometry}
          material={materials.phong63}
        />
      </group>
      <mesh
        geometry={nodes.Object_776.geometry}
        material={materials.phong15}
        position={[-0.8, 0.4, 0.1]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[2.6, 0.1, 1.5]}
      />
      <mesh
        geometry={nodes.Object_779.geometry}
        material={materials.phong14}
        position={[-0.4, 0.5, 0.9]}
        rotation={[0, 0.1, 0]}
        scale={[0.5, 0.1, 0.5]}
      />
      <mesh
        geometry={nodes.Object_782.geometry}
        material={materials.phong15}
        position={[0.8, 0.4, 0.1]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[2.6, 0.1, 1.5]}
      />
      <mesh
        geometry={nodes.Object_786.geometry}
        material={materials.phong9}
        position={[-0.1, -0.1, -1.6]}
        rotation={[0, 0.3, 0]}
        scale={1.1}
      />
      <mesh
        geometry={nodes.Object_789.geometry}
        material={materials.phong14}
        position={[-0.5, 0.5, -0.6]}
        rotation={[0, Math.PI / 9, 0]}
        scale={[0.5, 0.1, 0.5]}
      />
      <mesh
        geometry={nodes.Object_792.geometry}
        material={materials.phong14}
        position={[1, 0.5, -0.7]}
        rotation={[0, -0.3, 0]}
        scale={[0.5, 0.1, 0.5]}
      />
      <mesh
        geometry={nodes.Object_795.geometry}
        material={materials.phong14}
        position={[1.1, 0.5, 0.7]}
        rotation={[0, 0.2, 0]}
        scale={[0.5, 0.1, 0.5]}
      />
      <mesh
        geometry={nodes.Object_798.geometry}
        material={materials.phong7}
        position={[-0.2, 0, 0]}
        scale={[1, 1, 1.1]}
      />
      <mesh
        geometry={nodes.Object_814.geometry}
        material={materials.phong7}
        position={[-0.4, 0, -1.6]}
        rotation={[0, Math.PI / 9, 0]}
        scale={[1, 1, 1.1]}
      />
      <group position={[-0.7, 0, -1.8]} rotation={[0, Math.PI / 4, 0]}>
        <mesh
          geometry={nodes.Object_818.geometry}
          material={materials.phong11}
        />
        <mesh
          geometry={nodes.Object_821.geometry}
          material={materials.phong10}
        />
        <mesh
          geometry={nodes.Object_824.geometry}
          material={materials.phong61}
        />
        <mesh
          geometry={nodes.Object_827.geometry}
          material={materials.phong12}
        />
      </group>
      <mesh
        geometry={nodes.Object_830.geometry}
        material={materials.phong7}
        position={[1.5, 0, -1.4]}
        rotation={[0, -0.2, 0]}
        scale={[1, 1, 1.1]}
      />
      <group position={[1.2, 0, -1.7]} rotation={[0, 0.2, 0]}>
        <mesh
          geometry={nodes.Object_834.geometry}
          material={materials.phong11}
        />
        <mesh
          geometry={nodes.Object_837.geometry}
          material={materials.phong10}
        />
        <mesh
          geometry={nodes.Object_840.geometry}
          material={materials.phong61}
        />
        <mesh
          geometry={nodes.Object_843.geometry}
          material={materials.phong12}
        />
      </group>
      <mesh
        geometry={nodes.Object_846.geometry}
        material={materials.phong7}
        position={[1.1, 0, -0.3]}
        rotation={[0, Math.PI / 9, 0]}
        scale={[1, 1, 1.1]}
      />
      <group position={[0.9, 0, -0.5]} rotation={[0, Math.PI / 4, 0]}>
        <mesh
          geometry={nodes.Object_850.geometry}
          material={materials.phong11}
        />
        <mesh
          geometry={nodes.Object_853.geometry}
          material={materials.phong10}
        />
        <mesh
          geometry={nodes.Object_856.geometry}
          material={materials.phong61}
        />
        <mesh
          geometry={nodes.Object_859.geometry}
          material={materials.phong12}
        />
      </group>
      <mesh
        geometry={nodes.Object_1729.geometry}
        material={materials.phong7}
        position={[0.6, 0.8, 2.4]}
        rotation={[-Math.PI, Math.PI / 4, -1.7]}
        scale={[0.9, 1, 1]}
      />
      <group position={[3.7, 0, 0]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh
          geometry={nodes.Object_1733.geometry}
          material={materials.phong46}
        />
        <mesh
          geometry={nodes.Object_1735.geometry}
          material={materials.phong27}
        />
        <mesh
          geometry={nodes.Object_1738.geometry}
          material={materials.phong45}
        />
        <mesh
          geometry={nodes.Object_1740.geometry}
          material={materials.phong46}
        />
        <mesh
          geometry={nodes.Object_1742.geometry}
          material={materials.phong27}
        />
      </group>
      <group position={[0, 0, 2.7]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh
          geometry={nodes.Object_1745.geometry}
          material={materials.phong45}
        />
        <mesh
          geometry={nodes.Object_1747.geometry}
          material={materials.phong46}
        />
        <mesh
          geometry={nodes.Object_1749.geometry}
          material={materials.phong27}
        />
      </group>
      <group position={[-0.3, 0, -0.1]} rotation={[0, Math.PI / 2, 0]}>
        <mesh
          geometry={nodes.Object_1766.geometry}
          material={materials.phong27}
        />
        <mesh
          geometry={nodes.Object_1768.geometry}
          material={materials.phong45}
        />
        <mesh
          geometry={nodes.Object_1770.geometry}
          material={materials.phong46}
        />
      </group>
      <group position={[1.8, 0.6, 0.4]} scale={0.1}>
        <mesh
          geometry={nodes.Object_1773.geometry}
          material={materials.phong19}
        />
        <mesh
          geometry={nodes.Object_1775.geometry}
          material={materials.phong53}
        />
        <mesh
          geometry={nodes.Object_1777.geometry}
          material={materials.phong54}
        />
      </group>
      <group position={[1.8, 0.6, -0.4]} scale={0.1}>
        <mesh
          geometry={nodes.Object_1780.geometry}
          material={materials.phong19}
        />
        <mesh
          geometry={nodes.Object_1782.geometry}
          material={materials.phong53}
        />
        <mesh
          geometry={nodes.Object_1784.geometry}
          material={materials.phong54}
        />
      </group>
      <group position={[1.8, 0.6, 0]} scale={0.1}>
        <mesh
          geometry={nodes.Object_1787.geometry}
          material={materials.phong19}
        />
        <mesh
          geometry={nodes.Object_1789.geometry}
          material={materials.phong53}
        />
        <mesh
          geometry={nodes.Object_1791.geometry}
          material={materials.phong54}
        />
      </group>
      <group position={[1.8, 0.6, -0.8]} scale={0.1}>
        <mesh
          geometry={nodes.Object_1794.geometry}
          material={materials.phong19}
        />
        <mesh
          geometry={nodes.Object_1796.geometry}
          material={materials.phong53}
        />
        <mesh
          geometry={nodes.Object_1798.geometry}
          material={materials.phong54}
        />
      </group>
      <group
        position={[0, -0.3, 0]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[4.2, 0.2, 3.4]}
      >
        <mesh
          geometry={nodes.Object_1801.geometry}
          material={materials.phong55}
        />
        <mesh
          geometry={nodes.Object_1803.geometry}
          material={materials.phong24}
        />
        <mesh
          geometry={nodes.Object_1805.geometry}
          material={materials.phong56}
        />
      </group>
      <group position={[-0.3, 0, -1.6]} rotation={[0, 0.4, 0]}>
        <mesh
          geometry={nodes.Object_1819.geometry}
          material={materials.phong9}
        />
        <mesh
          geometry={nodes.Object_1821.geometry}
          material={materials.phong58}
        />
        <mesh
          geometry={nodes.Object_1823.geometry}
          material={materials.phong60}
        />
        <mesh
          geometry={nodes.Object_1825.geometry}
          material={materials.phong59}
        />
        <mesh
          geometry={nodes.Object_1827.geometry}
          material={materials.phong32}
        />
      </group>
      <group position={[1.3, 0, -1.7]} rotation={[0, 0.2, 0]}>
        <mesh
          geometry={nodes.Object_1830.geometry}
          material={materials.phong9}
        />
        <mesh
          geometry={nodes.Object_1832.geometry}
          material={materials.phong58}
        />
        <mesh
          geometry={nodes.Object_1834.geometry}
          material={materials.phong60}
        />
        <mesh
          geometry={nodes.Object_1836.geometry}
          material={materials.phong59}
        />
        <mesh
          geometry={nodes.Object_1838.geometry}
          material={materials.phong32}
        />
      </group>
      <group position={[1.3, 0, -0.3]} rotation={[0, Math.PI / 9, 0]}>
        <mesh
          geometry={nodes.Object_1841.geometry}
          material={materials.phong9}
        />
        <mesh
          geometry={nodes.Object_1843.geometry}
          material={materials.phong58}
        />
        <mesh
          geometry={nodes.Object_1845.geometry}
          material={materials.phong60}
        />
        <mesh
          geometry={nodes.Object_1847.geometry}
          material={materials.phong59}
        />
        <mesh
          geometry={nodes.Object_1849.geometry}
          material={materials.phong32}
        />
      </group>
      <mesh geometry={nodes.Object_170.geometry} material={materials.phong24} />
      <mesh geometry={nodes.Object_172.geometry} material={materials.phong57} />
      <mesh geometry={nodes.Object_174.geometry} material={materials.phong55} />
      <mesh geometry={nodes.Object_176.geometry} material={materials.phong36} />
      <mesh
        geometry={nodes.Object_194.geometry}
        material={materials.phong4}
        position={[0, -1.2, 0]}
        scale={[1, 1.6, 1]}
      />
      <mesh geometry={nodes.Object_180.geometry} material={materials.phong4} />
      <mesh geometry={nodes.Object_183.geometry} material={materials.phong3} />
      <mesh geometry={nodes.Object_186.geometry} material={materials.phong3} />
      <mesh geometry={nodes.Object_189.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_191.geometry} material={materials.phong40} />
      <mesh geometry={nodes.Object_197.geometry} material={materials.phong3} />
      <mesh geometry={nodes.Object_200.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_202.geometry} material={materials.phong40} />
      <group position={[-1.9, 1.1, 0]} rotation={[0, 0, -Math.PI / 3]}>
        <mesh
          geometry={nodes.Object_631.geometry}
          material={materials.phong5}
        />
        <mesh
          geometry={nodes.Object_633.geometry}
          material={materials.phong52}
        />
      </group>
      <group position={[1.9, 1.1, 0]} rotation={[0, 0, Math.PI / 3]}>
        <mesh
          geometry={nodes.Object_636.geometry}
          material={materials.phong5}
        />
        <mesh
          geometry={nodes.Object_638.geometry}
          material={materials.phong52}
        />
      </group>
      <group position={[-1.9, 3.3, 0]} rotation={[0, 0, -2.1]}>
        <mesh
          geometry={nodes.Object_641.geometry}
          material={materials.phong5}
        />
        <mesh
          geometry={nodes.Object_643.geometry}
          material={materials.phong52}
        />
      </group>
      <group position={[1.9, 3.3, 0]} rotation={[0, 0, 2.1]}>
        <mesh
          geometry={nodes.Object_646.geometry}
          material={materials.phong5}
        />
        <mesh
          geometry={nodes.Object_648.geometry}
          material={materials.phong52}
        />
      </group>
      <group position={[0, 4.4, 0]} rotation={[0, 0, -Math.PI]}>
        <mesh
          geometry={nodes.Object_651.geometry}
          material={materials.phong5}
        />
        <mesh
          geometry={nodes.Object_653.geometry}
          material={materials.phong52}
        />
      </group>
      <mesh geometry={nodes.Object_617.geometry} material={materials.phong5} />
      <mesh geometry={nodes.Object_620.geometry} material={materials.phong5} />
      <mesh geometry={nodes.Object_623.geometry} material={materials.phong49} />
      <mesh geometry={nodes.Object_626.geometry} material={materials.phong5} />
      <mesh geometry={nodes.Object_628.geometry} material={materials.phong52} />
      <mesh geometry={nodes.Object_802.geometry} material={materials.phong11} />
      <mesh geometry={nodes.Object_805.geometry} material={materials.phong10} />
      <mesh geometry={nodes.Object_808.geometry} material={materials.phong61} />
      <mesh geometry={nodes.Object_811.geometry} material={materials.phong12} />
      <mesh geometry={nodes.Object_863.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_865.geometry} material={materials.phong40} />
      <mesh geometry={nodes.Object_868.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_870.geometry} material={materials.phong40} />
      <mesh geometry={nodes.Object_873.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_875.geometry} material={materials.phong40} />
      <mesh geometry={nodes.Object_878.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_880.geometry} material={materials.phong40} />
      <mesh geometry={nodes.Object_883.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_885.geometry} material={materials.phong40} />
      <mesh geometry={nodes.Object_888.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_890.geometry} material={materials.phong40} />
      <mesh geometry={nodes.Object_893.geometry} material={materials.phong25} />
      <mesh geometry={nodes.Object_896.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_898.geometry} material={materials.phong40} />
      <mesh geometry={nodes.Object_901.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_904.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_907.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_910.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_913.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_915.geometry} material={materials.phong40} />
      <mesh geometry={nodes.Object_918.geometry} material={materials.phong25} />
      <mesh geometry={nodes.Object_921.geometry} material={materials.phong26} />
      <mesh geometry={nodes.Object_924.geometry} material={materials.phong25} />
      <mesh geometry={nodes.Object_927.geometry} material={materials.phong26} />
      <mesh geometry={nodes.Object_930.geometry} material={materials.phong25} />
      <mesh geometry={nodes.Object_933.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_936.geometry} material={materials.phong26} />
      <mesh geometry={nodes.Object_939.geometry} material={materials.phong25} />
      <mesh geometry={nodes.Object_942.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_945.geometry} material={materials.phong26} />
      <mesh geometry={nodes.Object_948.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_951.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_954.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_957.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_959.geometry} material={materials.phong40} />
      <mesh geometry={nodes.Object_962.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_965.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_968.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_971.geometry} material={materials.phong25} />
      <mesh geometry={nodes.Object_974.geometry} material={materials.phong26} />
      <mesh geometry={nodes.Object_977.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_980.geometry} material={materials.phong25} />
      <mesh geometry={nodes.Object_983.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_986.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_989.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_992.geometry} material={materials.phong26} />
      <mesh geometry={nodes.Object_995.geometry} material={materials.phong25} />
      <mesh geometry={nodes.Object_998.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1001.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1004.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1007.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1010.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1013.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1016.geometry}
        material={materials.phong25}
      />
      <mesh
        geometry={nodes.Object_1019.geometry}
        material={materials.phong25}
      />
      <mesh geometry={nodes.Object_1022.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1025.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1027.geometry}
        material={materials.phong40}
      />
      <mesh
        geometry={nodes.Object_1030.geometry}
        material={materials.phong25}
      />
      <mesh geometry={nodes.Object_1033.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1036.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1039.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1042.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1045.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1047.geometry}
        material={materials.phong40}
      />
      <mesh geometry={nodes.Object_1050.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1052.geometry}
        material={materials.phong40}
      />
      <mesh geometry={nodes.Object_1055.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1058.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1061.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1064.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1067.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1070.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1072.geometry}
        material={materials.phong40}
      />
      <mesh
        geometry={nodes.Object_1075.geometry}
        material={materials.phong25}
      />
      <mesh
        geometry={nodes.Object_1078.geometry}
        material={materials.phong42}
      />
      <mesh
        geometry={nodes.Object_1080.geometry}
        material={materials.phong41}
      />
      <mesh
        geometry={nodes.Object_1082.geometry}
        material={materials.phong25}
      />
      <mesh
        geometry={nodes.Object_1085.geometry}
        material={materials.phong25}
      />
      <mesh
        geometry={nodes.Object_1088.geometry}
        material={materials.phong25}
      />
      <mesh
        geometry={nodes.Object_1090.geometry}
        material={materials.phong41}
      />
      <mesh geometry={nodes.Object_1093.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1095.geometry}
        material={materials.phong40}
      />
      <mesh geometry={nodes.Object_1098.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1100.geometry}
        material={materials.phong40}
      />
      <mesh
        geometry={nodes.Object_1103.geometry}
        material={materials.phong25}
      />
      <mesh
        geometry={nodes.Object_1105.geometry}
        material={materials.phong41}
      />
      <mesh
        geometry={nodes.Object_1108.geometry}
        material={materials.phong25}
      />
      <mesh
        geometry={nodes.Object_1110.geometry}
        material={materials.phong41}
      />
      <mesh
        geometry={nodes.Object_1113.geometry}
        material={materials.phong25}
      />
      <mesh
        geometry={nodes.Object_1115.geometry}
        material={materials.phong41}
      />
      <mesh
        geometry={nodes.Object_1118.geometry}
        material={materials.phong25}
      />
      <mesh
        geometry={nodes.Object_1120.geometry}
        material={materials.phong41}
      />
      <mesh
        geometry={nodes.Object_1123.geometry}
        material={materials.phong25}
      />
      <mesh
        geometry={nodes.Object_1125.geometry}
        material={materials.phong41}
      />
      <mesh geometry={nodes.Object_1128.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1130.geometry}
        material={materials.phong40}
      />
      <mesh
        geometry={nodes.Object_1133.geometry}
        material={materials.phong25}
      />
      <mesh
        geometry={nodes.Object_1135.geometry}
        material={materials.phong41}
      />
      <mesh
        geometry={nodes.Object_1138.geometry}
        material={materials.phong25}
      />
      <mesh
        geometry={nodes.Object_1140.geometry}
        material={materials.phong41}
      />
      <mesh
        geometry={nodes.Object_1143.geometry}
        material={materials.phong25}
      />
      <mesh
        geometry={nodes.Object_1145.geometry}
        material={materials.phong41}
      />
      <mesh geometry={nodes.Object_1148.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1150.geometry}
        material={materials.phong40}
      />
      <mesh geometry={nodes.Object_1153.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1156.geometry}
        material={materials.phong26}
      />
      <mesh geometry={nodes.Object_1159.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1162.geometry}
        material={materials.phong26}
      />
      <mesh
        geometry={nodes.Object_1165.geometry}
        material={materials.phong25}
      />
      <mesh geometry={nodes.Object_1168.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1171.geometry}
        material={materials.phong26}
      />
      <mesh geometry={nodes.Object_1174.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1177.geometry}
        material={materials.phong26}
      />
      <mesh geometry={nodes.Object_1180.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1183.geometry}
        material={materials.phong25}
      />
      <mesh geometry={nodes.Object_1186.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1189.geometry}
        material={materials.phong26}
      />
      <mesh geometry={nodes.Object_1192.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1195.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1198.geometry}
        material={materials.phong25}
      />
      <mesh geometry={nodes.Object_1201.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1204.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1207.geometry}
        material={materials.phong26}
      />
      <mesh geometry={nodes.Object_1210.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1213.geometry}
        material={materials.phong26}
      />
      <mesh geometry={nodes.Object_1216.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1219.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1222.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1224.geometry}
        material={materials.phong40}
      />
      <mesh geometry={nodes.Object_1227.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1230.geometry}
        material={materials.phong25}
      />
      <mesh geometry={nodes.Object_1233.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1235.geometry}
        material={materials.phong40}
      />
      <mesh
        geometry={nodes.Object_1238.geometry}
        material={materials.phong25}
      />
      <mesh geometry={nodes.Object_1241.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1243.geometry}
        material={materials.phong40}
      />
      <mesh geometry={nodes.Object_1246.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1248.geometry}
        material={materials.phong40}
      />
      <mesh
        geometry={nodes.Object_1251.geometry}
        material={materials.phong25}
      />
      <mesh
        geometry={nodes.Object_1253.geometry}
        material={materials.phong41}
      />
      <mesh
        geometry={nodes.Object_1256.geometry}
        material={materials.phong25}
      />
      <mesh
        geometry={nodes.Object_1258.geometry}
        material={materials.phong41}
      />
      <mesh
        geometry={nodes.Object_1261.geometry}
        material={materials.phong25}
      />
      <mesh
        geometry={nodes.Object_1263.geometry}
        material={materials.phong41}
      />
      <mesh geometry={nodes.Object_1266.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1268.geometry}
        material={materials.phong40}
      />
      <mesh geometry={nodes.Object_1271.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1273.geometry}
        material={materials.phong40}
      />
      <mesh geometry={nodes.Object_1276.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1278.geometry}
        material={materials.phong40}
      />
      <mesh geometry={nodes.Object_1281.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1283.geometry}
        material={materials.phong40}
      />
      <mesh geometry={nodes.Object_1286.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1288.geometry}
        material={materials.phong40}
      />
      <mesh geometry={nodes.Object_1291.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1293.geometry}
        material={materials.phong40}
      />
      <mesh geometry={nodes.Object_1296.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1298.geometry}
        material={materials.phong40}
      />
      <mesh geometry={nodes.Object_1301.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1303.geometry}
        material={materials.phong40}
      />
      <mesh geometry={nodes.Object_1306.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1309.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1311.geometry}
        material={materials.phong40}
      />
      <mesh
        geometry={nodes.Object_1314.geometry}
        material={materials.phong25}
      />
      <mesh geometry={nodes.Object_1317.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1320.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1323.geometry}
        material={materials.phong25}
      />
      <mesh
        geometry={nodes.Object_1326.geometry}
        material={materials.phong25}
      />
      <mesh geometry={nodes.Object_1329.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1332.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1335.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1338.geometry}
        material={materials.phong25}
      />
      <mesh
        geometry={nodes.Object_1341.geometry}
        material={materials.phong25}
      />
      <mesh
        geometry={nodes.Object_1344.geometry}
        material={materials.phong26}
      />
      <mesh
        geometry={nodes.Object_1347.geometry}
        material={materials.phong26}
      />
      <mesh geometry={nodes.Object_1350.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1353.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1356.geometry}
        material={materials.phong25}
      />
      <mesh geometry={nodes.Object_1359.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1362.geometry}
        material={materials.phong25}
      />
      <mesh
        geometry={nodes.Object_1365.geometry}
        material={materials.phong26}
      />
      <mesh geometry={nodes.Object_1368.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1371.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1374.geometry}
        material={materials.phong25}
      />
      <mesh geometry={nodes.Object_1377.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1380.geometry}
        material={materials.phong25}
      />
      <mesh
        geometry={nodes.Object_1383.geometry}
        material={materials.phong26}
      />
      <mesh
        geometry={nodes.Object_1386.geometry}
        material={materials.phong25}
      />
      <mesh geometry={nodes.Object_1389.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1392.geometry}
        material={materials.phong25}
      />
      <mesh geometry={nodes.Object_1395.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1398.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1401.geometry}
        material={materials.phong26}
      />
      <mesh geometry={nodes.Object_1404.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1407.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1410.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1412.geometry}
        material={materials.phong40}
      />
      <mesh geometry={nodes.Object_1415.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1417.geometry}
        material={materials.phong40}
      />
      <mesh geometry={nodes.Object_1420.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1422.geometry}
        material={materials.phong40}
      />
      <mesh geometry={nodes.Object_1425.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1428.geometry}
        material={materials.phong25}
      />
      <mesh geometry={nodes.Object_1431.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1434.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1437.geometry}
        material={materials.phong26}
      />
      <mesh
        geometry={nodes.Object_1440.geometry}
        material={materials.phong25}
      />
      <mesh geometry={nodes.Object_1443.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1446.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1449.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1452.geometry}
        material={materials.phong25}
      />
      <mesh
        geometry={nodes.Object_1455.geometry}
        material={materials.phong26}
      />
      <mesh geometry={nodes.Object_1458.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1461.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1464.geometry}
        material={materials.phong25}
      />
      <mesh
        geometry={nodes.Object_1467.geometry}
        material={materials.phong25}
      />
      <mesh geometry={nodes.Object_1470.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1473.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1476.geometry}
        material={materials.phong25}
      />
      <mesh geometry={nodes.Object_1479.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1482.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1485.geometry}
        material={materials.phong26}
      />
      <mesh geometry={nodes.Object_1488.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1491.geometry}
        material={materials.phong25}
      />
      <mesh
        geometry={nodes.Object_1494.geometry}
        material={materials.phong25}
      />
      <mesh
        geometry={nodes.Object_1497.geometry}
        material={materials.phong26}
      />
      <mesh
        geometry={nodes.Object_1500.geometry}
        material={materials.phong26}
      />
      <mesh geometry={nodes.Object_1503.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1506.geometry}
        material={materials.phong25}
      />
      <mesh geometry={nodes.Object_1509.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1512.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1515.geometry}
        material={materials.phong26}
      />
      <mesh geometry={nodes.Object_1518.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1521.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1524.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1527.geometry}
        material={materials.phong25}
      />
      <mesh geometry={nodes.Object_1530.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1533.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1536.geometry}
        material={materials.phong25}
      />
      <mesh geometry={nodes.Object_1539.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1542.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1545.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1548.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1551.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1554.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1556.geometry}
        material={materials.phong40}
      />
      <mesh geometry={nodes.Object_1559.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1561.geometry}
        material={materials.phong40}
      />
      <mesh geometry={nodes.Object_1564.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1566.geometry}
        material={materials.phong40}
      />
      <mesh geometry={nodes.Object_1569.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1571.geometry}
        material={materials.phong40}
      />
      <mesh geometry={nodes.Object_1574.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1576.geometry}
        material={materials.phong40}
      />
      <mesh geometry={nodes.Object_1579.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1581.geometry}
        material={materials.phong40}
      />
      <mesh geometry={nodes.Object_1584.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1586.geometry}
        material={materials.phong40}
      />
      <mesh geometry={nodes.Object_1589.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1591.geometry}
        material={materials.phong40}
      />
      <mesh geometry={nodes.Object_1594.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1596.geometry}
        material={materials.phong40}
      />
      <mesh geometry={nodes.Object_1599.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1601.geometry}
        material={materials.phong40}
      />
      <mesh geometry={nodes.Object_1604.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1606.geometry}
        material={materials.phong40}
      />
      <mesh geometry={nodes.Object_1609.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1612.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1614.geometry}
        material={materials.phong40}
      />
      <mesh
        geometry={nodes.Object_1617.geometry}
        material={materials.phong25}
      />
      <mesh geometry={nodes.Object_1620.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1623.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1625.geometry}
        material={materials.phong40}
      />
      <mesh geometry={nodes.Object_1628.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1630.geometry}
        material={materials.phong40}
      />
      <mesh geometry={nodes.Object_1633.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1636.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1638.geometry}
        material={materials.phong40}
      />
      <mesh geometry={nodes.Object_1641.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1644.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1647.geometry}
        material={materials.phong25}
      />
      <mesh geometry={nodes.Object_1650.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1652.geometry}
        material={materials.phong40}
      />
      <mesh
        geometry={nodes.Object_1655.geometry}
        material={materials.phong25}
      />
      <mesh
        geometry={nodes.Object_1658.geometry}
        material={materials.phong25}
      />
      <mesh geometry={nodes.Object_1661.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1664.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1667.geometry}
        material={materials.phong26}
      />
      <mesh
        geometry={nodes.Object_1670.geometry}
        material={materials.phong25}
      />
      <mesh
        geometry={nodes.Object_1673.geometry}
        material={materials.phong25}
      />
      <mesh geometry={nodes.Object_1676.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1678.geometry}
        material={materials.phong40}
      />
      <mesh geometry={nodes.Object_1681.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1684.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1687.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1689.geometry}
        material={materials.phong40}
      />
      <mesh geometry={nodes.Object_1692.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1695.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1698.geometry}
        material={materials.phong26}
      />
      <mesh geometry={nodes.Object_1701.geometry} material={materials.phong1} />
      <mesh geometry={nodes.Object_1704.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1706.geometry}
        material={materials.phong40}
      />
      <mesh geometry={nodes.Object_1709.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1711.geometry}
        material={materials.phong40}
      />
      <mesh geometry={nodes.Object_1714.geometry} material={materials.phong1} />
      <mesh
        geometry={nodes.Object_1717.geometry}
        material={materials.phong25}
      />
      <mesh
        geometry={nodes.Object_1720.geometry}
        material={materials.phong25}
      />
      <mesh
        geometry={nodes.Object_1723.geometry}
        material={materials.phong25}
      />
      <mesh
        geometry={nodes.Object_1726.geometry}
        material={materials.phong25}
      />
      <mesh
        geometry={nodes.Object_1752.geometry}
        material={materials.phong46}
      />
      <mesh
        geometry={nodes.Object_1754.geometry}
        material={materials.phong27}
      />
      <mesh
        geometry={nodes.Object_1756.geometry}
        material={materials.phong45}
      />
      <mesh
        geometry={nodes.Object_1759.geometry}
        material={materials.phong27}
      />
      <mesh
        geometry={nodes.Object_1761.geometry}
        material={materials.phong45}
      />
      <mesh
        geometry={nodes.Object_1763.geometry}
        material={materials.phong46}
      />
      <mesh geometry={nodes.Object_1808.geometry} material={materials.phong9} />
      <mesh
        geometry={nodes.Object_1810.geometry}
        material={materials.phong58}
      />
      <mesh
        geometry={nodes.Object_1812.geometry}
        material={materials.phong60}
      />
      <mesh
        geometry={nodes.Object_1814.geometry}
        material={materials.phong59}
      />
      <mesh
        geometry={nodes.Object_1816.geometry}
        material={materials.phong32}
      />
      <mesh
        geometry={nodes.Object_1852.geometry}
        material={materials.phong58}
      />
      <mesh
        geometry={nodes.Object_1854.geometry}
        material={materials.phong59}
      />
      <mesh geometry={nodes.Object_1856.geometry} material={materials.phong9} />
    </a.group>
  );
};

export default Island;
